spring:
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
    format:
      date: iso
      date-time: iso
      time: iso
  application:
    name: operator-service
  data:
    mongodb:
      uri: mongodb://localhost:27017/operatordb
eureka:
  client:
    serviceUrl:
      defaultZone: ${EUREKA_CLIENT_SERVICEURL_DEFAULTZONE}

logging:
  level:
    com.netflix.discovery: DEBUG
    org.springframework.cloud: DEBUG


