spring:
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
    format:
      date: iso
      date-time: iso
      time: iso
  application:
    name: flight-search-service
eureka:
  client:
    serviceUrl:
      defaultZone: ${EUREKA_CLIENT_SERVICEURL_DEFAULTZONE}


