spring:
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
    format:
      date: iso
      date-time: iso
      time: iso
  application:
    name: flight-search-service
  data:
    mongodb:
      uri: mongodb://mongodb:27017/flightsearchdb