apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    service: schema-registry
  name: schema-registry
spec:
  replicas: 1
  selector:
    matchLabels:
      service: schema-registry
  template:
    metadata:
      labels:
        service: schema-registry
        network/kafka-network: "true"
    spec:
      containers:
        - name: schema-registry
          imagePullPolicy: IfNotPresent
          image: confluentinc/cp-schema-registry:latest
          ports:
            - containerPort: 8081
          env:
            - name: SCHEMA_REGISTRY_HOST_NAME
              value: "schema-registry"
            - name: SCHEMA_REGISTRY_LISTENERS
              value: "http://0.0.0.0:8081"
            - name: SCHEMA_REGISTRY_KAFKASTORE_CONNECTION_URL
              value: "zookeeper-service:2181"
            - name: SCHEMA_REGISTRY_KAFKASTORE_BOOTSTRAP_SERVERS
              value: "kafka-service:29092"
            - name: SCHEMA_REGISTRY_DEBUG
              value: "true"

