apiVersion: v1
kind: Service
metadata:
  labels:
    service: mongodb-service
  name: mongodb-external-service
spec:
  type: NodePort
  selector:
    service: mongodb
  ports:
    - port: 27017
      targetPort: 27017